"""
Step 4: 五行分析 (Five Elements Analysis)

Calculates element distribution, strength judgment, and useful god
determination based on the Four Pillars.

Key concepts:
- 天干五行: Each heavenly stem maps to an element
- 地支藏干: Each earthly branch contains hidden stems with weights
- 日主强弱: Day master strength judged by element support
- 用神: The element that balances the chart
"""

from typing import Dict, Optional, List

from .types import Pillar, FourPillars, ElementDistribution

# ─── 天干五行映射 ───────────────────────────────────────────────
STEM_ELEMENT: dict[str, str] = {
    "甲": "wood", "乙": "wood",
    "丙": "fire", "丁": "fire",
    "戊": "earth", "己": "earth",
    "庚": "metal", "辛": "metal",
    "壬": "water", "癸": "water",
}

# ─── 地支五行映射 ───────────────────────────────────────────────
BRANCH_ELEMENT: dict[str, str] = {
    "寅": "wood", "卯": "wood",
    "巳": "fire", "午": "fire",
    "辰": "earth", "戌": "earth", "丑": "earth", "未": "earth",
    "申": "metal", "酉": "metal",
    "子": "water", "亥": "water",
}

# ─── 地支藏干 (Hidden Stems with weights) ──────────────────────
# Weight: 1.0 = primary (本气), 0.6 = secondary (中气), 0.3 = tertiary (余气), 0.1 = residual
BRANCH_HIDDEN_STEMS: dict[str, dict[str, float]] = {
    "子": {"癸": 1.0},
    "丑": {"己": 0.6, "癸": 0.3, "辛": 0.1},
    "寅": {"甲": 0.6, "丙": 0.3, "戊": 0.1},
    "卯": {"乙": 1.0},
    "辰": {"戊": 0.6, "乙": 0.3, "癸": 0.1},
    "巳": {"丙": 0.6, "庚": 0.3, "戊": 0.1},
    "午": {"丁": 0.6, "己": 0.3},
    "未": {"己": 0.6, "丁": 0.3, "乙": 0.1},
    "申": {"庚": 0.6, "壬": 0.3, "戊": 0.1},
    "酉": {"辛": 1.0},
    "戌": {"戊": 0.6, "辛": 0.3, "丁": 0.1},
    "亥": {"壬": 0.6, "甲": 0.3},
}

# ─── 五行生克关系 ───────────────────────────────────────────────
# 相生 (Generates): wood→fire→earth→metal→water→wood
GENERATES: dict[str, str] = {
    "wood": "fire", "fire": "earth", "earth": "metal",
    "metal": "water", "water": "wood",
}

# 相克 (Weakens/Controls): wood→metal→fire→water→earth→wood
WEAKENS: dict[str, str] = {
    "wood": "metal", "fire": "water", "earth": "wood",
    "metal": "fire", "water": "earth",
}

# 生我 (Generated by): reverse of GENERATES
GENERATED_BY: dict[str, str] = {v: k for k, v in GENERATES.items()}

# 克我 (Weakened by): reverse of WEAKENS
WEAKENED_BY: dict[str, str] = {v: k for k, v in WEAKENS.items()}

# 地支助力 (Branches that support each element)
SUPPORTIVE_BRANCHES: dict[str, list[str]] = {
    "wood": ["寅", "卯"],
    "fire": ["巳", "午"],
    "earth": ["辰", "戌", "丑", "未"],
    "metal": ["申", "酉"],
    "water": ["子", "亥"],
}


def calculate_element_distribution(pillars: FourPillars) -> ElementDistribution:
    """
    Calculate the distribution of Five Elements (五行占比).

    Rules:
        - Each heavenly stem in the pillars contributes weight 1.0
        - Each hidden stem in earthly branches contributes its weight
        - Weights are accumulated for wood, fire, earth, metal, water
    """
    dist = ElementDistribution()

    # Collect all non-None pillars
    pillars_list: List[Pillar] = [pillars.year, pillars.month, pillars.day]
    if pillars.hour:
        pillars_list.append(pillars.hour)

    for pillar in pillars_list:
        # 天干 contribution
        stem_element = STEM_ELEMENT.get(pillar.stem)
        if stem_element:
            current = getattr(dist, stem_element)
            setattr(dist, stem_element, current + 1.0)

        # 地支藏干 contribution
        hidden = BRANCH_HIDDEN_STEMS.get(pillar.branch, {})
        for stem, weight in hidden.items():
            element = STEM_ELEMENT.get(stem)
            if element:
                current = getattr(dist, element)
                setattr(dist, element, current + weight)

    return dist


def judge_strength(
    day_stem: str,
    dist: ElementDistribution,
    month_branch: str,
) -> str:
    """
    Judge the day master's strength (日主强弱).

    Factors:
        - Count of the same element (比劫)
        - Count of elements that generate the day master (印星)
        - Season support (月令)
        - Score threshold: strong > 40, weak < 20, else balanced

    Returns: "strong" | "weak" | "balanced"
    """
    day_element = STEM_ELEMENT.get(day_stem, "earth")

    # 同我 (same element support)
    same = getattr(dist, day_element, 0)

    # 生我 (generating element support)
    generating = getattr(dist, GENERATED_BY.get(day_element, ""), 0)

    # Season bonus: month branch element support
    month_element = BRANCH_ELEMENT.get(month_branch, "")
    season_bonus = 5 if month_element == day_element else 0

    support_score = same + generating * 0.7 + season_bonus

    if support_score > 40:
        return "strong"
    elif support_score < 20:
        return "weak"
    return "balanced"


# ─── 用神判断 ───────────────────────────────────────────────────
WEAKENING_ELEMENT: dict[str, str] = {
    "wood": "metal", "fire": "water", "earth": "wood",
    "metal": "fire", "water": "earth",
}

SUPPORTING_ELEMENT: dict[str, str] = {
    "wood": "water", "fire": "wood", "earth": "fire",
    "metal": "earth", "water": "metal",
}


def determine_useful_god(strength: str, day_element: str) -> str:
    """
    Determine the Useful God (用神).

    Rules:
        - Strong day master → use controlling element (克我)
        - Weak day master → use generating element (生我)
        - Balanced → no dominant god needed
    """
    if strength == "strong":
        return WEAKENING_ELEMENT.get(day_element, "earth")
    elif strength == "weak":
        return SUPPORTING_ELEMENT.get(day_element, "water")
    return "balanced_no_dominant_god"
